<Dashboard>
	name: "dashboard"

    on_enter:
        root.start_ping()
	
    id001: id001
    router001: router001
	dvr001: dvr001
	gate001: gate001
   
    id002: id002
	router002: router002
	dvr002: dvr002
	gate002: gate002

    id003: id003
	dvr003: dvr003
	gate003: gate003
	router003: router003

    id004: id004
	dvr004: dvr004
	gate004: gate004
	router004: router004

    id005: id005
    dvr005: dvr005
    gate005: gate005
    router005: router005

    id006: id006
	dvr006: dvr006
	gate006: gate006
	router006: router006

    id007: id007
	dvr007: dvr007
	gate007: gate007
	router007: router007

    id008: id008
	dvr008: dvr008
	gate008: gate008
	router008: router008

    id009: id009
	dvr009: dvr009
	gate009: gate009
	router009: router009

    id010: id010
	dvr010: dvr010
	gate010: gate010
	router010: router010

    id011: id011
	dvr011: dvr011
	gate011: gate011
	router011: router011

    id012: id012	
	dvr012: dvr012
	gate012: gate012
	router012: router012

    id013: id013	
	dvr013: dvr013
	gate013: gate013
	router013: router013

    id014: id014
    dvr014: dvr014
    gate014: gate014
    router014: router014

    id015: id015	
	dvr015: dvr015
	gate015: gate015
	router015: router015

    id016: id016	
	dvr016: dvr016
	gate016: gate016
	router016: router016

    id017: id017	
	dvr017: dvr017
	gate017: gate017
	router017: router017

    id018: id018
	dvr018: dvr018
	gate018: gate018
	router018: router018

    id020: id020	
	dvr020: dvr020
	gate020: gate020
	router020: router020

    id021: id021	
    dvr021: dvr021
    gate021: gate021
    router021: router021

    id022: id022
	dvr022: dvr022
	gate022: gate022
	router022: router022

    id023: id023	
	dvr023: dvr023
	gate023: gate023
	router023: router023

    id024: id024	
	dvr024: dvr024
	gate024: gate024
	router024: router024

    id025: id025
    dvr025: dvr025
    gate025: gate025
    router025: router025

    id026: id026	
	dvr026: dvr026
	gate026: gate026
	router026: router026

    id027: id027	
	dvr027: dvr027
	gate027: gate027
	router027: router027

    id028: id028	
	dvr028: dvr028
	gate028: gate028
	router028: router028

    id029: id029	
	dvr029: dvr029
	gate029: gate029
	router029: router029

    id030: id030	
	dvr030: dvr030
	gate030: gate030
	router030: router030

    id031: id031	
	dvr031: dvr031
	gate031: gate031
	router031: router031

    id032: id032	
	dvr032: dvr032
	gate032: gate032
	router032: router032

    id033: id033	
	dvr033: dvr033
	gate033: gate033
	router033: router033

    id034: id034	
	dvr034: dvr034
	gate034: gate034
	router034: router034

    id035: id035	
	dvr035: dvr035
	gate035: gate035
	router035: router035

    id036: id036	
	dvr036: dvr036
	gate036: gate036
	router036: router036

    id037: id037
    dvr037: dvr037
    gate037: gate037
    router037: router037

    id038: id038	
	dvr038: dvr038
	gate038: gate038
	router038: router038

    id039: id039	
	dvr039: dvr039
	gate039: gate039
	router039: router039

    id040: id040	
	dvr040: dvr040
	gate040: gate040
	router040: router040

    id044: id044	
	dvr044: dvr044
	gate044: gate044
	router044: router044

    id045: id045	
	dvr045: dvr045
	gate045: gate045
	router045: router045

    id046: id046	
	dvr046: dvr046
	gate046: gate046
	router046: router046

    id047: id047	
	dvr047: dvr047
	gate047: gate047
	router047: router047

    id059: id059	
	dvr059: dvr059
	gate059: gate059
	router059: router059

    id060: id060	
	dvr060: dvr060
	gate060: gate060
	router060: router060

    id061: id061	
	dvr061: dvr061
	gate061: gate061
	router061: router061

    id062: id062
    dvr062: dvr062
    gate062: gate062
    router062: router062

    id070: id070
    dvr070: dvr070
    gate070: gate070
    router070: router070

    id071: id071
    dvr071: dvr071
    gate071: gate071
    router071: router071

    id171: id171
    dvr171: dvr171
    gate171: gate171
    router171: router171

    id172: id172
    dvr172: dvr172
    gate172: gate172
    router172: router172

    id173: id173
    dvr173: dvr173
    gate173: gate173
    router173: router173

    id174: id174
    dvr174: dvr174
    gate174: gate174
    router174: router174

    id175: id175
    dvr175: dvr175
    gate175: gate175
    router175: router175

    id177: id177
    dvr177: dvr177
    gate177: gate177
    router177: router177

    id178: id178
    dvr178: dvr178
    gate178: gate178
    router178: router178

    id201: id201
    dvr201: dvr201
    gate201: gate201
    router201: router201

    id202: id202
    dvr202: dvr202
    gate202: gate202
    router202: router202

    id203: id203
    dvr203: dvr203
    gate203: gate203
    router203: router203

    id204: id204
    dvr204: dvr204
    gate204: gate204
    router204: router204

    id301: id301
    dvr301: dvr301
    gate301: gate301
    router301: router301

    id302: id302
    dvr302: dvr302
    gate302: gate302
    router302: router302

    id303: id303
    dvr303: dvr303
    gate303: gate303
    router303: router303

    id304: id304
    dvr304: dvr304
    gate304: gate304
    router304: router304

    id305: id305
    dvr305: dvr305
    gate305: gate305
    router305: router305

    id306: id306
    dvr306: dvr306
    gate306: gate306
    router306: router306

    id307: id307
    dvr307: dvr307
    gate307: gate307
    router307: router307

    id308: id308
    dvr308: dvr308
    gate308: gate308
    router308: router308

    id309: id309
    dvr309: dvr309
    gate309: gate309
    router309: router309

    id310: id310
    dvr310: dvr310
    gate310: gate310
    router310: router310

    id311: id311
    dvr311: dvr311
    gate311: gate311
    router311: router311

    id312: id312
    dvr312: dvr312
    gate312: gate312
    router312: router312

    id313: id313
    dvr313: dvr313
    gate313: gate313
    router313: router313

    id314: id314
    dvr314: dvr314
    gate314: gate314
    router314: router314

    id315: id315
    dvr315: dvr315
    gate315: gate315
    router315: router315

    id316: id316
    dvr316: dvr316
    gate316: gate316
    router316: router316

    id317: id317
    dvr317: dvr317
    gate317: gate317
    router317: router317

    id352: id352
    dvr352: dvr352
    gate352: gate352
    router352: router352

    id354: id354
    dvr354: dvr354
    gate354: gate354
    router354: router354

    id355: id355
    dvr355: dvr355
    gate355: gate355
    router355: router355

    id402: id402
    dvr402: dvr402
    gate402: gate402
    router402: router402

    id403: id403
    dvr403: dvr403
    gate403: gate403
    router403: router403

    id425: id425
    dvr425: dvr425
    gate425: gate425
    router425: router425

    id428: id428
    dvr428: dvr428
    gate428: gate428
    router428: router428

    id429: id429
    dvr429: dvr429
    gate429: gate429
    router429: router429

    id432: id432
    dvr432: dvr432
    gate432: gate432
    router432: router432

    id433: id433
    dvr433: dvr433
    gate433: gate433
    router433: router433

    id434: id434
    dvr434: dvr434
    gate434: gate434
    router434: router434

    id435: id435
    dvr435: dvr435
    gate435: gate435
    router435: router435

    id436: id436
    dvr436: dvr436
    gate436: gate436
    router436: router436

    id437: id437
    dvr437: dvr437
    gate437: gate437
    router437: router437

    id438: id438
    dvr438: dvr438
    gate438: gate438
    router438: router438

    id439: id439
    dvr439: dvr439
    gate439: gate439
    router439: router439

    id440: id440
    dvr440: dvr440
    gate440: gate440
    router440: router440

    id443: id443
    dvr443: dvr443
    gate443: gate443
    router443: router443

    id444: id444
    dvr444: dvr444
    gate444: gate444
    router444: router444

    id445: id445
    dvr445: dvr445
    gate445: gate445
    router445: router445

    id450: id450
    dvr450: dvr450
    gate450: gate450
    router450: router450

    id451: id451
    dvr451: dvr451
    gate451: gate451
    router451: router451

    id452: id452
    dvr452: dvr452
    gate452: gate452
    router452: router452

    id453: id453
    dvr453: dvr453
    gate453: gate453
    router453: router453

    id454: id454
    dvr454: dvr454
    gate454: gate454
    router454: router454

    id455: id455
    dvr455: dvr455
    gate455: gate455
    router455: router455

    id456: id456
    dvr456: dvr456
    gate456: gate456
    router456: router456

    id501: id501
    dvr501: dvr501
    gate501: gate501
    router501: router501

    id502: id502
    dvr502: dvr502
    gate502: gate502
    router502: router502

    id503: id503
    dvr503: dvr503
    gate503: gate503
    router503: router503

    id504: id504
    dvr504: dvr504
    gate504: gate504
    router504: router504

    id505: id505
    dvr505: dvr505
    gate505: gate505
    router505: router505

    id506: id506
    dvr506: dvr506
    gate506: gate506
    router506: router506

    id507: id507
    dvr507: dvr507
    gate507: gate507
    router507: router507
	
	canvas.before:
		Color:
			rgba: 1, 1, 1, .2
		Rectangle:
			pos: (self.x, self.y)
			size: (self.width, self.height)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (640, 0)
			size: (5, 2000)
		Rectangle:
			pos: (1280, 0)
			size: (5, 2000)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (0, 1037.5)
			size: (2000, 1)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (0, 1010.5)
			size: (2000, 1)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (0, 982.5)
			size: (2000, 1)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (0, 955.5)
			size: (2000, 1)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (0, 928.5)
			size: (2000, 1)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (0, 901.5)
			size: (2000, 1)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (0, 874.5)
			size: (2000, 1)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (0, 847.5)
			size: (2000, 1)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (0, 820.5)
			size: (2000, 1)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (0, 793.5)
			size: (2000, 1)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (0, 766.5)
			size: (2000, 1)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (0, 739.5)
			size: (2000, 1)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (0, 712.5)
			size: (2000, 1)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (0, 685.5)
			size: (2000, 1)
		Color:
			rgba: (1, 1, 1, 1)
		Rectangle:
			pos: (0, 658.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 631.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 604.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 577.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 550.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 523.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 496.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 469.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 442.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 415)
			size: (2000, 1)
		Rectangle:
			pos: (0, 388.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 361.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 334.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 307.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 280.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 253.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 226.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 199.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 172.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 145.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 118.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 91.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 64.5)
			size: (2000, 1)
		Rectangle:
			pos: (0, 37.5)
			size: (2000, 1)



	FloatLayout:

        Label:
            id: id001
            text:"001:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.9}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
        	id: router001
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.9}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr001
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.9}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate001
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.9}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id002
            text:"002:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.875}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router002
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.875}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr002
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.875}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
        	id: gate002
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.875}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id003
            text:"003:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.850}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router003
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.85}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr003
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.85}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate003
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.85}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id004
            text:"004:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.825}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router004
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.825}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr004
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.825}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate004
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.825}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id005
            text:"005:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.8}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router005
            text:"Router"
            font_size: 0
            pos_hint: {"x":-0.185, "y":.8}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr005
            text:"DVR"
            font_size: 0
            pos_hint: {"x":-0.08, "y":.8}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate005
            text:"Gate Controller"
            font_size: 0
            pos_hint: {"x":0.045, "y":.8}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id006
            text:"006:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.775}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router006
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.775}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr006
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.775}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate006
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.775}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
		Label:
            id: id007
            text:"007:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.75}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
        	id: router007
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.75}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr007
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.75}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate007
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.75}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id008
            text:"008:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.725}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router008
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.725}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr008
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.725}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate008
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.725}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id009
            text:"009:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.70}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router009
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.70}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr009
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.70}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate009
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.70}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id010
            text:"010:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.675}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router010
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.675}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr010
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.675}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate010
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.675}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id011
            text:"011:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.65}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router011
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.65}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr011
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.65}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate011
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.65}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id012
            text:"012:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.625}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router012
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.625}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr012
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.625}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate012
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.625}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id013
            text:"013:"
            font_size: 20
            pos_hint: {'x':-0.235, 'y':.60}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router013
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.60}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr013
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.60}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate013
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.60}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id014
            text:"014:"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.55}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router014
            text:"Router"
            font_size: 0
            pos_hint: {"x":-0.185, "y":.575}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr014
            text:"DVR"
            font_size: 0
            pos_hint: {"x":-0.08, "y":.575}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate014
            text:"Gate Controller"
            font_size: 0
            pos_hint: {"x":0.045, "y":.575}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id015
            text:"015:"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.55}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router015
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.55}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr015
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.55}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate015
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.55}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id016
            text:"016:"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.55}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router016
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.575}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr016
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.575}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate016
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.575}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id017
            text:"017:"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.55}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router017
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.55}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr017
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.55}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate017
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.55}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id018
            text:"018:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.525}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router018
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.525}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr018
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.525}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate018
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.525}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id020
            text:"020:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.5}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router020
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.5}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr020
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.5}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate020
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.5}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id021
            text:"021:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.5}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router021
            text:"Router"
            font_size: 0
            pos_hint: {"x":-0.185, "y":.5}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr021
            text:"DVR"
            font_size: 0
            pos_hint: {"x":-0.08, "y":.5}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate021
            text:"Gate Controller"
            font_size: 0
            pos_hint: {"x":0.045, "y":.5}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id022
            text:"022:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.475}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router022
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.475}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr022
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.475}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate022
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.475}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id023
            text:"023:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.45}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router023
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.45}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr023
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.45}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate023
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.45}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id024
            text:"024:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.425}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router024
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.425}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr024
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.425}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
        	id: gate024
            text:"Gate Controller"
            font_size: 0
            pos_hint: {"x":0.036, "y":.425}
            size_hint: 0.5, 0.15
            color: 1,1,1,.5
            bold: True

        Label:
            id: id025
            text:"025:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.5}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router025
            text:"Router"
            font_size: 0
            pos_hint: {"x":-0.185, "y":.5}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr025
            text:"DVR"
            font_size: 0
            pos_hint: {"x":-0.08, "y":.5}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate025
            text:"Gate Controller"
            font_size: 0
            pos_hint: {"x":0.045, "y":.5}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id026
            text:"026:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router026
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr026
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate026
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id027
            text:"027:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.375}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router027
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.375}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr027
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.375}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate027
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.375}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id028
            text:"028:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.35}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router028
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.35}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr028
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.35}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate028
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.35}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id029
            text:"029:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.325}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router029
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.325}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr029
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.325}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate029
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.325}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id030
            text:"030:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.3}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router030
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.3}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr030
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.3}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate030
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.3}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id031
            text:"031:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.275}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router031
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.275}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr031
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.275}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate031
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.275}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id032
            text:"032:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.25}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
        	id: router032
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.25}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr032
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.25}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate032
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.25}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id033
            text:"033:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.225}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router033
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.225}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr033
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.225}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate033
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.225}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id034
            text:"034:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.2}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router034
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.2}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr034
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.2}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate034
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.2}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id035
            text:"035:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.175}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router035
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.175}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr035
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.175}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate035
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.175}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id036
            text:"036:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.150}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router036
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.15}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr036
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.15}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate036
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.15}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id037
            text:"037:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.150}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router037
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.15}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr037
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.15}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate037
            text:"Gate Controller"
            font_size: 0
            pos_hint: {"x":0.045, "y":.15}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id038
            text:"038:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.125}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router038
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.125}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr038
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.125}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate038
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.125}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id039
            text:"039:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.1}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router039
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.1}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr039
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.1}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate039
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.1}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id040
            text:"040:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":0.075}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router040
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.075}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr040
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.075}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate040
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.075}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id044
            text:"044:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.05}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router044
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.05}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr044
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.05}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate044
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.05}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id045
            text:"045:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":.025}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router045
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.025}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr045
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.025}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate045
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.025}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id046
            text:"046:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":0}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router046
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":0}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr046
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":0}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate046
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":0}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id047
            text:"047:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":-0.025}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router047
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":-0.025}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr047
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":-0.025}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate047
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":-0.025}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id059
            text:"059:"
            font_size: 20
            pos_hint: {"x":-0.235, "y":-0.05}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router059
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":-0.05}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr059
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":-0.05}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate059
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":-0.05}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id060
            text:"060:"
            font_size: 20
            pos_hint: {"x":.1, "y":0.9}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router060
            text:"Router"
            font_size: 20
            pos_hint: {"x":0.14, "y":.9}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True


        Label:
            id: dvr060
            text:"DVR"
            font_size: 20
            pos_hint: {"x":0.24, "y":.9}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate060
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.38, "y":.9}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id061
            text:"061:"
            font_size: 20
            pos_hint: {"x":.1, "y":0.875}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router061
            text:"Router"
            font_size: 20
            pos_hint: {"x":0.14, "y":.875}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True


        Label:
            id: dvr061
            text:"DVR"
            font_size: 20
            pos_hint: {"x":0.24, "y":.875}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate061
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.38, "y":.875}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id062
            text:"062:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.85}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router062
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr062
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate062
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id070
            text:"070:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.825}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router070
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr070
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate070
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id071
            text:"071:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.8}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router071
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr071
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate071
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id171
            text:"171:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.775}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router171
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr171
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate171
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id172
            text:"172:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.75}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router172
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr172
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate172
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id173
            text:"173:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.725}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router173
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr173
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate173
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id174
            text:"174:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.7}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router174
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr174
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate174
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id175
            text:"175:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.675}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router175
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr175
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate175
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

		Label:
            id: id177
            text:"177:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.650}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router177
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr177
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate177
            text:"Gate Controller"
            font_size: 0
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id178
            text:"178:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.625}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router178
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr178
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate178
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id201
            text:"201:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.6}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router201
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr201
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate201
            text:"Gate Controller"
            font_size: 0
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id202
            text:"202:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.6}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router202
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr202
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate202
            text:"Gate Controller"
            font_size: 0
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True



        Label:
            id: id203
            text:"203:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.6}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router203
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr203
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate203
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id204
            text:"204:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.575}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router204
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr204
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate204
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id301
            text:"301:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.55}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router301
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr301
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate301
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id302
            text:"302:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.525}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router302
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr302
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate302
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id303
            text:"303:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.5}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router303
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr303
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate303
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id304
            text:"304:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.475}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router304
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr304
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate304
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id305
            text:"305:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.45}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router305
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr305
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate305
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id306
            text:"306:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.425}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router306
            text:"Router"
            font_size: 0
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr306
            text:"DVR"
            font_size: 0
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate306
            text:"Gate Controller"
            font_size: 0
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id307
            text:"307:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.425}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router307
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr307
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate307
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id308
            text:"308:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router308
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr308
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate308
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id309
            text:"309:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.375}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router309
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr309
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate309
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id310
            text:"310:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.35}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router310
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr310
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate310
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id311
            text:"311:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.325}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True
        Label:
            id: router311
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr311
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate311
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id312
            text:"312:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.3}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router312
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr312
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate312
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id313
            text:"313:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.275}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router313
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr313
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate313
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id314
            text:"314:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.25}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router314
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr314
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate314
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id315
            text:"315:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.225}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router315
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr315
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate315
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id316
            text:"316:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.2}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router316
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr316
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate316
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id317
            text:"317:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.175}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router317
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr317
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate317
            text:"Gate Controller"
            font_size: 0
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id352
            text:"352:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.15}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router352
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr352
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate352
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id354
            text:"354:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.125}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router354
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr354
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate354
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id355
            text:"355:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.1}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router355
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr355
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate355
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id402
            text:"402:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.6}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router402
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr402
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate402
            text:"Gate Controller"
            font_size: 0
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True


        Label:
            id: id403
            text:"403:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.075}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router403
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr403
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate403
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id425
            text:"425:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.05}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router425
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr425
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate425
            text:"Gate Controller"
            font_size: 0
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id428
            text:"428:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.025}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router428
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr428
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate428
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id429
            text:"429:"
            font_size: 20
            pos_hint: {"x":0.1, "y":.0}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router429
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr429
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate429
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id432
            text:"432:"
            font_size: 20
            pos_hint: {"x":0.1, "y":-0.025}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router432
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr432
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate432
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id433
            text:"433:"
            font_size: 20
            pos_hint: {"x":0.1, "y":-0.05}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router433
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr433
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate433
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id434
            text:"434:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.9}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router434
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr434
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate434
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id435
            text:"435:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.875}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router435
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr435
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate435
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id436
            text:"436:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.85}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router436
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr436
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate436
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id437
            text:"437:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.825}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router437
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr437
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate437
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id438
            text:"438:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.8}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router438
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr438
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate438
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id439
            text:"439:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.775}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router439
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr439
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate439
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id440
            text:"440:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.75}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router440
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr440
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate440
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id443
            text:"443:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.725}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router443
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr443
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate443
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id444
            text:"444:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.7}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router444
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr444
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate444
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id445
            text:"445:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.675}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router445
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr445
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate445
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id450
            text:"450:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.65}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router450
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr450
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate450
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id451
            text:"451:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.625}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router451
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr451
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate451
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True
        Label:
            id: id452
            text:"452:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.6}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router452
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr452
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate452
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id453
            text:"453:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.575}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router453
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr453
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate453
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id454
            text:"454:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.55}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router454
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr454
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate454
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id455
            text:"455:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.525}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router455
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr455
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate455
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id456
            text:"456:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.5}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router456
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr456
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate456
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id501
            text:"501:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.475}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router501
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr501
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate501
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id502
            text:"502:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.45}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router502
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr502
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate502
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id503
            text:"503:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.425}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router503
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr503
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate503
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True


        Label:
            id: id504
            text:"504:"
            font_size: 20
            pos_hint: {"x":0.432, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router504
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr504
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate504
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id505
            text:"505:"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.55}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router505
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr505
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate505
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id506
            text:"506:"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.55}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router506
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr506
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate506
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: id507
            text:"507:"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.55}
            size_hint: 0.5, 0.15
            color: 1,1,1,1
            underline: True
            bold: True

        Label:
            id: router507
            text:"Router"
            font_size: 20
            pos_hint: {"x":-0.185, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: dvr507
            text:"DVR"
            font_size: 20
            pos_hint: {"x":-0.08, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True

        Label:
            id: gate507
            text:"Gate Controller"
            font_size: 20
            pos_hint: {"x":0.045, "y":.4}
            size_hint: 0.5, 0.15
            color: 1,.5,.2,1
            bold: True



